name: showdoom
version: '0.1.0.0'
category: Games
author: Christian Fischer
maintainer: christian@chfi.se
copyright: 2017 Christian Fischer
license: BSD3
homepage: https://github.com/chfi/showdoom#readme

extra-source-files:
- README.md

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- GeneralizedNewtypeDeriving
- DeriveFunctor
- RecordWildCards

ghc-options:
- -Wall
- -threaded

dependencies:
- base >=4.7 && <5
# - classy-prelude >=1.2.0.1 && <1.3
# - brick >=0.17 && <0.18
# - vty >=5.15 && <5.16
# - bytestring >=0.10.8 && <0.11
# - attoparsec >=0.13.1 && <0.14
# - lens >=4.15.1 && <4.16
# - linear >=1.20.6 && <1.21
- classy-prelude >=1.2
- brick
- vty
- bytestring
- attoparsec
- lens
- linear
- vector
- errors

library:
  source-dirs: src
  exposed-modules:
  - Doom.Map
  - Doom.UI.Directory
  - Doom.UI.Lump
  - Doom.WAD
  - Doom.WAD.Types
  dependencies:
  - text >=1.2.2 && <1.3
  - binary >=0.8.3 && <0.9

executables:
  showdoom:
    main: Main.hs
    source-dirs: app
    dependencies:
    - showdoom
    - optparse-applicative >=0.13.2 && <0.14
    - gl >=0.8.0 && <0.9
    - GLFW-b >=1.4.8.1 && <1.5
    - JuicyPixels >=3.2.8.2 && <3.3
